Repository pesto-students/batch-9-Lumen, pull requests merged in 2019-09, with the labels that each got.

#182 feat(client): design category type page
  client/src/components/BlogCard/BlogCard.module.css
  client/src/containers/CategoryType/CategoryType.jsx
  client/src/containers/CategoryType/CategoryType.module.css
Labels: feature, frontend

#184 feat(client): add markdown instruction helper
  client/src/components/Form/BlogsInputs/BlogsMarkdownInput.jsx
  client/src/components/MarkdownInstructions/MarkdownInstructions.jsx
Labels: feature, frontend

#188 fix(client): comment profile wrong username link
  client/src/components/Comment/index.jsx
  server/views/shareBlog.ejs
Labels: bug

#196 fix: reply fix, chore: delete blog, fix:auth modal css
  client/src/apis/blogs.js
  client/src/components/Comment/CommentComponent.jsx
  client/src/components/Comment/index.jsx
  client/src/components/UI/Modal/Modal.module.css
  client/src/components/ViewBlog/ShareBlog.jsx
  client/src/components/blogBox/preview.jsx
  client/src/components/deleteBlog/index.jsx
  server/src/controller/apis/blogs.js
  server/src/middlewares/blogs.js
  server/src/middlewares/comments.js
  server/src/middlewares/votes.js
  server/src/services/comments/service.js
  server/src/services/votes/service.js
Labels: backend, bug, enhancement, feature, frontend

#201 fix(client): comment default image, blog user image, reply bug
  client/src/components/Comment/CommentComponent.jsx
  client/src/components/Comment/Reply.jsx
  client/src/components/Comment/index.jsx
  client/src/components/ViewBlog/ViewBlog.jsx
  client/src/components/ViewBlog/ViewBlog.module.css
  server/src/models/user.js
Labels: bug, enhancement, feature

#203 fix(server): Top blogs api blog count
  server/src/services/blogs/api.js
  server/src/services/votes/service.js
Labels: backend, bug
