Repository pesto-students/batch-9-Lumen, pull requests merged in 2019-08, with the labels that each got.

#34 setup: mono-repo
  .gitignore
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  package.json
  server/index.js
  server/package.json
  server/src/__tests__/index.test.js
  server/yarn.lock
  yarn.lock
Labels: Setup

#35 chore(.github): create PR checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Setup

#40 setup: setup eslint and husky
  .eslintignore
  .eslintrc.json
  client/package.json
  client/yarn.lock
  package.json
  server/yarn.lock
  yarn.lock
Labels: Setup

#41 feat(server):add versioned api structure
  server/README.md
  server/index.js
  server/package.json
  server/src/__tests__/README.md
  server/src/__tests__/index.test.js
  server/src/configs/README.md
  server/src/configs/app.js
  server/src/controller/README.md
  server/src/controller/apis/README.md
  server/src/controller/apis/user.js
  server/src/routes/README.md
  server/src/routes/index.js
  server/src/routes/rest/README.md
  server/src/routes/rest/index.js
  server/src/routes/rest/v1.js
  server/src/services/README.md
  server/src/services/user/api.js
  server/src/utils/logger.js
  server/yarn.lock
Labels: feature

#38 docs(.circleci):CircleCi config docs
  .circleci/README.md
Labels: documentation

#43 feat(server): add database schema models
  server/src/models/blogs.js
  server/src/models/user.js
Labels: feature

#44 feat (client): react layout
  client/package.json
  client/src/App.js
  client/src/App.jsx
  client/src/App.test.jsx
  client/src/components/Logo/Logo.jsx
  client/src/components/Logo/Logo.module.css
  client/src/components/Navigation/NavigationItems/NavigationItem/NavigationItem.jsx
  client/src/components/Navigation/NavigationItems/NavigationItem/NavigationItem.module.css
  client/src/components/Navigation/NavigationItems/NavigationItems.jsx
  client/src/components/Navigation/NavigationItems/NavigationItems.module.css
  client/src/components/Navigation/Toolbar/Toolbar.jsx
  client/src/components/Navigation/Toolbar/Toolbar.module.css
  client/src/components/UI/Backdrop/Backdrop.jsx
  client/src/components/UI/Backdrop/Backdrop.module.css
  client/src/components/UI/Modal/Modal.jsx
  client/src/components/UI/Modal/Modal.module.css
  client/src/components/hoc/Layout/Layout.jsx
  client/src/components/hoc/Layout/Layout.module.css
  client/src/containers/Home.jsx
  client/src/index.js
  client/src/index.jsx
  client/src/test.png
  client/yarn.lock
Labels: feature

#49 feat(server): add blogs CRUD APIs flow
  server/package.json
  server/src/configs/README.md
  server/src/configs/app.js
  server/src/configs/authentication.js
  server/src/controller/apis/README.md
  server/src/controller/apis/blogs.js
  server/src/middlewares/README.md
  server/src/middlewares/blogs.js
  server/src/routes/rest/v1.js
  server/src/services/README.md
  server/src/services/blogs/api.js
  server/yarn.lock
Labels: feature

#74 fix(env): import env variables from one file
  server/src/configs/app.js
  server/src/configs/env.js
Labels: feature

#72 ci: setup continuous deployment of server to Heroku
  .circleci/config.yml
  Procfile
Labels: Setup, feature

#52 feat(server): add signin and signup api
  server/index.js
  server/jest.config.js
  server/package.json
  server/src/.babelrc
  server/src/__tests__/routes/users/index.test.js
  server/src/__tests__/utils/validations/index.test.js
  server/src/configs/app.js
  server/src/configs/authentication.js
  server/src/configs/database.js
  server/src/configs/env.js
  server/src/controller/apis/user.js
  server/src/middlewares/user.js
  server/src/models/user.js
  server/src/services/user/service.js
  server/src/utils/hashing/config.js
  server/src/utils/hashing/index.js
  server/src/utils/helpers/bcrypt.js
  server/src/utils/tokenization/config.js
  server/src/utils/validations/addErrorIfEmpty.js
  server/src/utils/validations/errorForProperties.js
  server/src/utils/validations/index.js
  server/src/utils/validations/isEmpty.js
  server/src/utils/validations/signIn.js
  server/src/utils/validations/signUp.js
  server/yarn.lock
Labels: feature

#65 feat(client): design homepage and FAB
  client/package.json
  client/src/App.jsx
  client/src/components/Blog.jsx
  client/src/components/FloatingActionButton/FloatingActionButton.jsx
  client/src/components/FloatingActionButton/FloatingActionButton.module.css
  client/src/components/Logo/Logo.jsx
  client/src/containers/Home.jsx
  client/src/containers/Home.module.css
  client/src/index.jsx
  client/yarn.lock
Labels: feature

#90 fix(config.yml): change ssh access to https
  .circleci/config.yml
Labels: bug

#75 feat(client):add video support in markdown
  client/package.json
  client/src/components/markdownRenderer/plugins/index.js
  client/src/components/markdownRenderer/plugins/video.js
  client/src/components/markdownRenderer/renderers/index.jsx
  client/src/components/markdownRenderer/renderers/video.jsx
  client/yarn.lock
Labels: enhancement

#94 docs(README.md): add eslint and husky documentation
  ESLINT_README.md
  HUSKY_README.md
  README.md
Labels: documentation

#91 feat(server): add votes apis
  server/src/__tests__/routes/votes/index.test.js
  server/src/controller/apis/votes.js
  server/src/middlewares/blogs.js
  server/src/models/votes.js
  server/src/routes/rest/v1.js
  server/src/services/votes/api.js
  server/src/services/votes/service.js
  server/src/utils/helpers/mongoose.js
Labels: backend, feature

#102 feat(client): Create BlogCard component for FrontPage
  client/src/components/BlogCard/index.jsx
  client/src/containers/Home.jsx
  client/src/containers/Home.module.css
  client/src/topTen.js
Labels: feature, frontend

#105 feat(.prettierrc): Setup prettier
  .eslintrc.json
  .prettierrc
  package.json
  yarn.lock
Labels: Build, feature

#101 feat(server): add comments apis
  server/src/__tests__/routes/comments/index.test.js
  server/src/controller/apis/comments.js
  server/src/middlewares/comments.js
  server/src/routes/rest/v1.js
  server/src/services/comments/api.js
  server/src/services/comments/service.js
Labels: backend, feature

#106 fix(server): fix validation issues
  server/src/__tests__/utils/validations/index.test.js
  server/src/utils/validations/addErrorIfNotValid.js
  server/src/utils/validations/email.js
  server/src/utils/validations/errorForProperties.js
  server/src/utils/validations/isNumber.js
  server/src/utils/validations/isString.js
  server/src/utils/validations/signIn.js
  server/src/utils/validations/signUp.js
Labels: backend, bug

#103 feat(server):add search api
  .gitignore
  server/package.json
  server/src/__tests__/services/blogs.test.js
  server/src/__tests__/testUtils/dummyData.js
  server/src/__tests__/testUtils/inMemoryDatabase.js
  server/src/controller/apis/blogs.js
  server/src/controller/apis/home.js
  server/src/middlewares/home.js
  server/src/services/blogs/api.js
  server/src/services/blogs/service.js
  server/src/services/home/api.js
  server/yarn.lock
Labels: backend, feature

#108 feat(client): add new logo
  client/public/logo192.png
  client/public/logo512.png
  client/src/components/Logo/Logo.jsx
  client/src/components/Logo/Logo.module.css
  client/src/components/Logo/LumenLogoBlack.png
  client/src/components/Logo/LumenLogoWhite.png
Labels: frontend

#114 feat(client): Update CSS of BlogCard Component
  client/src/components/BlogCard/index.jsx
  client/src/containers/Home.jsx
  client/src/customStyles.css
Labels: enhancement, frontend

#110 feat(client): Add create and preview blog component.
  client/package.json
  client/src/components/Form/BlogsInputs/BlogsCategorySelect.jsx
  client/src/components/Form/BlogsInputs/BlogsCoverImage.jsx
  client/src/components/Form/BlogsInputs/BlogsInputs.module.css
  client/src/components/Form/BlogsInputs/BlogsIsDraft.jsx
  client/src/components/Form/BlogsInputs/BlogsIsPublic.jsx
  client/src/components/Form/BlogsInputs/BlogsMarkdownInput.jsx
  client/src/components/Form/BlogsInputs/BlogsPreviewButton.jsx
  client/src/components/Form/BlogsInputs/BlogsTitleInput.jsx
  client/src/components/Form/BlogsInputs/index.js
  client/src/components/blogBox/index.jsx
  client/src/components/common/Checkbox.jsx
  client/src/components/common/Dropdown.jsx
  client/src/components/common/Form.jsx
  client/src/components/common/FormField.jsx
  client/src/components/common/Label.jsx
  client/src/components/common/PrimaryButton.jsx
  client/src/components/common/SearchableDropDown.jsx
  client/src/components/common/TextArea.jsx
  client/src/components/common/TextAreaAutoResize.jsx
  client/src/components/common/ToggleButton.jsx
  client/src/components/common/helpers/index.js
  client/src/hooks/useInput.js
  client/src/hooks/useToggle.js
  client/yarn.lock
Labels: feature, frontend

#134 fix: move update profile logic to redux
  client/src/components/ProfileDropdown/ProfileDropdown.jsx
  client/src/containers/Profile/EditProfile.jsx
  client/src/containers/Profile/index.jsx
  client/src/hooks/useGetUserBlogs.js
  client/src/hooks/useProfile.js
  client/src/http/axios-auth.js
  client/src/store/actions/actionTypes.js
  client/src/store/actions/authenticationActions.js
  client/src/store/actions/index.js
  client/src/store/reducers/authenticationReducer.js
  server/src/configs/authentication.js
  server/src/services/user/api.js
  server/src/services/user/service.js
Labels: bug, enhancement

#137 fix(server): add description to blog model and update api
  server/src/middlewares/blogs.js
  server/src/models/blogs.js
Labels: backend, enhancement

#138 feat(client): create blog page
  client/src/App.jsx
  client/src/containers/BlogPage/index.jsx
Labels: feature, frontend

#136 feat(client): integrate categories from backend
  client/src/apis/blogs.js
  client/src/components/MovableStackedCard/MovableStackedCard.jsx
  client/src/containers/Category/Category.jsx
  client/src/containers/CategoryType/CategoryType.jsx
  client/src/containers/Home/HomeExtended.jsx
  client/src/hooks/useSearchBlogs.js
  server/src/services/blogs/service.js
Labels: enhancement, feature, frontend

#140 feat:add top 10 blogs api and integrate home page
  client/src/apis/blogs.js
  client/src/containers/Home/Home.jsx
  client/src/hooks/useGetTopBlogs.js
  client/src/topTen.js
  server/src/controller/apis/blogs.js
  server/src/services/blogs/api.js
  server/src/services/blogs/service.js
  server/src/services/votes/service.js
Labels: backend, enhancement, feature, frontend

#147 feat(client): integrate comments apis with frontend components.
  client/package.json
  client/src/apis/comments.js
  client/src/components/Comment/CommentComponent.jsx
  client/src/components/Comment/Reply.jsx
  client/src/components/Comment/index.jsx
  client/src/constants/constants.js
  client/src/containers/BlogPage/index.jsx
  client/src/hooks/useComments.js
  client/src/hooks/useReplies.js
  client/src/http/axios-comments.js
  client/src/utils/date/fromNow.js
  client/src/utils/generateRandom.js
  client/yarn.lock
  server/src/services/comments/api.js
  server/src/services/comments/service.js
Labels: backend, frontend, important

#149 feature(react): design edit page
  client/src/components/Form/BlogsInputs/BlogDescriptionInput.jsx
  client/src/components/Form/BlogsInputs/BlogsCategorySelect.jsx
  client/src/components/Form/BlogsInputs/BlogsCoverImage.jsx
  client/src/components/Form/BlogsInputs/BlogsInputs.module.css
  client/src/components/Form/BlogsInputs/BlogsIsDraft.jsx
  client/src/components/Form/BlogsInputs/BlogsMarkdownInput.jsx
  client/src/components/Form/BlogsInputs/BlogsPreviewButton.jsx
  client/src/components/Form/BlogsInputs/index.js
  client/src/components/Form/FormInput.jsx
  client/src/components/Form/FormInput.module.css
  client/src/components/blogBox/blogBox.module.css
  client/src/components/blogBox/index.jsx
  client/src/components/blogBox/preview.jsx
  client/src/components/common/LabelButton.jsx
Labels: feature, frontend

#148 feat(client): Integrate draft and private url paths
  client/package.json
  client/src/App.jsx
  client/src/apis/blogs.js
  client/src/components/ViewBlog/ShareBlog.jsx
  client/src/components/ViewBlog/ViewBlog.jsx
  client/src/components/common/helpers/index.js
  client/src/containers/BlogPage/index.jsx
  client/src/hooks/useBlog.js
  client/yarn.lock
  server/src/controller/views/share.js
  server/src/middlewares/blogs.js
  server/src/services/blogs/service.js
Labels: backend, enhancement, feature, frontend

#160 feat(client): add loader for edit screen
  client/src/components/blogBox/index.jsx
Labels: enhancement, feature

#165 fix(client): use Votes hook updation fix
  client/src/components/Like/index.jsx
  client/src/hooks/useVotes.js
Labels: backend, bug, frontend, important

#173 feat(client): add updated lumen logo
  client/src/components/Logo/Logo.jsx
  client/src/components/Logo/Logo.module.css
Labels: enhancement, frontend

#171 fix(server): send top blogs and performance tweaked
  server/src/services/blogs/api.js
  server/src/services/blogs/service.js
Labels: backend, bug, enhancement, feature

#174 fix(client) homepage css and other tweaks
  client/src/components/ViewBlog/ViewBlog.jsx
  client/src/containers/Home/Home.jsx
  client/src/containers/Home/Home.module.css
  client/src/containers/Home/HomeExtended.module.css
  client/src/containers/Home/HomeLoader.jsx
  client/src/containers/Profile/ProfileBlogs.jsx
  client/src/containers/Profile/ProfileBlogs.module.css
  client/src/containers/Profile/ProfileBlogsPublic.jsx
  server/src/models/blogs.js
Labels: backend, bug, frontend

#176 fix(server): add decription to text index
  server/src/models/blogs.js
Labels: backend, bug, enhancement
